/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fuelin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author binak
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        initComponents();
        loadDashboard();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTotalTransaksi = new fuelin.PanelCustomRounded();
        lbTotalTransaksi = new javax.swing.JLabel();
        dispTotalTransaksi = new javax.swing.JLabel();
        pnTotalStok = new fuelin.PanelCustomRounded();
        lbTotalStok = new javax.swing.JLabel();
        dispTotalStok = new javax.swing.JLabel();
        pnLaporan = new fuelin.PanelCustomRounded();
        lbLaporan = new javax.swing.JLabel();
        dispLaporan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbTotalTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotalTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        lbTotalTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotalTransaksi.setText("Total Transaksi");

        dispTotalTransaksi.setBackground(new java.awt.Color(51, 51, 51));
        dispTotalTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dispTotalTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        dispTotalTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dispTotalTransaksi.setText("0");
        dispTotalTransaksi.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnTotalTransaksiLayout = new javax.swing.GroupLayout(pnTotalTransaksi);
        pnTotalTransaksi.setLayout(pnTotalTransaksiLayout);
        pnTotalTransaksiLayout.setHorizontalGroup(
            pnTotalTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTotalTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(dispTotalTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTotalTransaksiLayout.setVerticalGroup(
            pnTotalTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTotalTransaksiLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbTotalTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dispTotalTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbTotalStok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotalStok.setForeground(new java.awt.Color(51, 51, 51));
        lbTotalStok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotalStok.setText("Total Stok");

        dispTotalStok.setBackground(new java.awt.Color(51, 51, 51));
        dispTotalStok.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dispTotalStok.setForeground(new java.awt.Color(51, 51, 51));
        dispTotalStok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dispTotalStok.setText("0");
        dispTotalStok.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnTotalStokLayout = new javax.swing.GroupLayout(pnTotalStok);
        pnTotalStok.setLayout(pnTotalStokLayout);
        pnTotalStokLayout.setHorizontalGroup(
            pnTotalStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTotalStok, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(pnTotalStokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dispTotalStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTotalStokLayout.setVerticalGroup(
            pnTotalStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTotalStokLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbTotalStok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dispTotalStok, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbLaporan.setForeground(new java.awt.Color(51, 51, 51));
        lbLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLaporan.setText("Laporan");

        dispLaporan.setBackground(new java.awt.Color(51, 51, 51));
        dispLaporan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dispLaporan.setForeground(new java.awt.Color(51, 51, 51));
        dispLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dispLaporan.setText("0");
        dispLaporan.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnLaporanLayout = new javax.swing.GroupLayout(pnLaporan);
        pnLaporan.setLayout(pnLaporanLayout);
        pnLaporanLayout.setHorizontalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(pnLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dispLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLaporanLayout.setVerticalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLaporanLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dispLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnTotalTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(pnTotalStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(pnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTotalStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTotalTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(351, 351, 351))
        );
    }// </editor-fold>//GEN-END:initComponents
 void loadDashboard() {
        try (Connection conn = Koneksi.konek()) {

            // 1. Hitung total transaksi HARI INI
            String sqlTransaksi = "SELECT COUNT(*) FROM transaksi WHERE DATE(tanggal) = CURDATE()";
            PreparedStatement ps1 = conn.prepareStatement(sqlTransaksi);
            ResultSet rs1 = ps1.executeQuery();
            if (rs1.next()) {
                dispTotalTransaksi.setText(rs1.getInt(1) + "");
            }

            // 2. Hitung total stok tersedia (jumlah dari stok)
            String sqlStok = "SELECT SUM(jumlah_liter) FROM stok";
            PreparedStatement ps2 = conn.prepareStatement(sqlStok);
            ResultSet rs2 = ps2.executeQuery();
            if (rs2.next()) {
                dispTotalStok.setText(rs2.getInt(1) + "");
            }

            // 3. Hitung total laporan (jumlah transaksi seluruhnya)
            String sqlLaporan = "SELECT COUNT(*) FROM laporan";
            PreparedStatement ps3 = conn.prepareStatement(sqlLaporan);
            ResultSet rs3 = ps3.executeQuery();
            if (rs3.next()) {
                dispLaporan.setText(rs3.getInt(1) + "");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal memuat dashboard: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dispLaporan;
    private javax.swing.JLabel dispTotalStok;
    private javax.swing.JLabel dispTotalTransaksi;
    private javax.swing.JLabel lbLaporan;
    private javax.swing.JLabel lbTotalStok;
    private javax.swing.JLabel lbTotalTransaksi;
    private fuelin.PanelCustomRounded pnLaporan;
    private fuelin.PanelCustomRounded pnTotalStok;
    private fuelin.PanelCustomRounded pnTotalTransaksi;
    // End of variables declaration//GEN-END:variables
}
