/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fuelin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author binak
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        initComponents();
        loadDashboard();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnStokPertalite = new fuelin.PanelCustomRounded();
        lbStokPertalite = new javax.swing.JLabel();
        dispStokPertalite = new javax.swing.JLabel();
        pnStokPertamax = new fuelin.PanelCustomRounded();
        lbStokPertamax = new javax.swing.JLabel();
        dispStokPertamax = new javax.swing.JLabel();
        pnStokSolar = new fuelin.PanelCustomRounded();
        lbStokSolar = new javax.swing.JLabel();
        dispStokSolar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbStokPertalite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbStokPertalite.setForeground(new java.awt.Color(51, 51, 51));
        lbStokPertalite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStokPertalite.setText("Stok Pertalite");

        dispStokPertalite.setBackground(new java.awt.Color(51, 51, 51));
        dispStokPertalite.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dispStokPertalite.setForeground(new java.awt.Color(51, 51, 51));
        dispStokPertalite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dispStokPertalite.setText("0");
        dispStokPertalite.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnStokPertaliteLayout = new javax.swing.GroupLayout(pnStokPertalite);
        pnStokPertalite.setLayout(pnStokPertaliteLayout);
        pnStokPertaliteLayout.setHorizontalGroup(
            pnStokPertaliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbStokPertalite, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(dispStokPertalite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnStokPertaliteLayout.setVerticalGroup(
            pnStokPertaliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStokPertaliteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbStokPertalite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dispStokPertalite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbStokPertamax.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbStokPertamax.setForeground(new java.awt.Color(51, 51, 51));
        lbStokPertamax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStokPertamax.setText("Stok Pertamax");

        dispStokPertamax.setBackground(new java.awt.Color(51, 51, 51));
        dispStokPertamax.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dispStokPertamax.setForeground(new java.awt.Color(51, 51, 51));
        dispStokPertamax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dispStokPertamax.setText("0");
        dispStokPertamax.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnStokPertamaxLayout = new javax.swing.GroupLayout(pnStokPertamax);
        pnStokPertamax.setLayout(pnStokPertamaxLayout);
        pnStokPertamaxLayout.setHorizontalGroup(
            pnStokPertamaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbStokPertamax, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(pnStokPertamaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dispStokPertamax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnStokPertamaxLayout.setVerticalGroup(
            pnStokPertamaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStokPertamaxLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbStokPertamax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dispStokPertamax, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbStokSolar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbStokSolar.setForeground(new java.awt.Color(51, 51, 51));
        lbStokSolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStokSolar.setText("Stok Solar");

        dispStokSolar.setBackground(new java.awt.Color(51, 51, 51));
        dispStokSolar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dispStokSolar.setForeground(new java.awt.Color(51, 51, 51));
        dispStokSolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dispStokSolar.setText("0");
        dispStokSolar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnStokSolarLayout = new javax.swing.GroupLayout(pnStokSolar);
        pnStokSolar.setLayout(pnStokSolarLayout);
        pnStokSolarLayout.setHorizontalGroup(
            pnStokSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbStokSolar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(pnStokSolarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dispStokSolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnStokSolarLayout.setVerticalGroup(
            pnStokSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStokSolarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbStokSolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dispStokSolar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnStokPertalite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(pnStokPertamax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(pnStokSolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnStokSolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnStokPertamax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnStokPertalite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(351, 351, 351))
        );
    }// </editor-fold>//GEN-END:initComponents

    void loadDashboard() {
        try (Connection conn = Koneksi.konek()) {

            String sqlPertalite = "SELECT total_stok FROM bbm WHERE id_bbm = 'BBM001'";
            PreparedStatement ps1 = conn.prepareStatement(sqlPertalite);
            ResultSet rs1 = ps1.executeQuery();
            if (rs1.next()) {
                dispStokPertalite.setText(rs1.getInt(1) + " L");
            }

            String sqlPertamax = "SELECT total_stok FROM bbm WHERE id_bbm = 'BBM002'";
            PreparedStatement ps2 = conn.prepareStatement(sqlPertamax);
            ResultSet rs2 = ps2.executeQuery();
            if (rs2.next()) {
                dispStokPertamax.setText(rs2.getInt(1) + " L");
            }

            String sqlSolar = "SELECT total_stok FROM bbm WHERE id_bbm = 'BBM003'";
            PreparedStatement ps3 = conn.prepareStatement(sqlSolar);
            ResultSet rs3 = ps3.executeQuery();
            if (rs3.next()) {
                dispStokSolar.setText(rs3.getInt(1) + " L");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal memuat dashboard: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dispStokPertalite;
    private javax.swing.JLabel dispStokPertamax;
    private javax.swing.JLabel dispStokSolar;
    private javax.swing.JLabel lbStokPertalite;
    private javax.swing.JLabel lbStokPertamax;
    private javax.swing.JLabel lbStokSolar;
    private fuelin.PanelCustomRounded pnStokPertalite;
    private fuelin.PanelCustomRounded pnStokPertamax;
    private fuelin.PanelCustomRounded pnStokSolar;
    // End of variables declaration//GEN-END:variables
}
