/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fuelin;

import fuelin.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author binak
 */
public class Kas extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Kas() {
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        initComponents();
        reset();
        tampilTabel();
        tampilRingkasan();

    }

    void reset() {
        cbJenis.setSelectedItem(null);
        tfCatatan.setText(null);
        tfJumlah.setText(null);
        txtID.setText(null);
    }

    void tampilTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Jumlah");
        model.addColumn("Catatan");
        model.addColumn("Jenis");
        model.addColumn("Tanggal");

        String sql = "SELECT*FROM kas";
        try {
            Connection conn = Koneksi.konek();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                int id = rs.getInt("id_kas");
                String jumlah = rs.getString("jumlah");
                String catatan = rs.getString("catatan");
                String jenis = rs.getString("jenis");
                String tgl = rs.getString("waktu");
                Object[] baris = {id, jumlah, catatan, jenis, tgl};
                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data");
        }
        tbKas.setModel(model);
    }

    void tampilRingkasan() {
        String sql = "SELECT total_pendapatan, total_pengeluaran, saldo FROM v_ringkasan_kas";
        try {
            Connection conn = Koneksi.konek();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                double totalPendapatan = rs.getDouble("total_pendapatan");
                double totalPengeluaran = rs.getDouble("total_pengeluaran");
                double saldo = rs.getDouble("saldo");
                DecimalFormat formatter = new DecimalFormat("#,###.00");

                txtPendapatan.setText(formatter.format(totalPendapatan));
                txtPengeluaran.setText(formatter.format(totalPengeluaran));
                txtSaldo.setText(formatter.format(saldo));
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data: " + sQLException.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKas = new javax.swing.JPanel();
        lbJumlah = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        lbCatatan = new javax.swing.JLabel();
        tfCatatan = new javax.swing.JTextField();
        lbJenis = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        btnUbah = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKas = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPendapatan = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPengeluaran = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnKas.setBackground(new java.awt.Color(255, 255, 255));
        pnKas.setPreferredSize(new java.awt.Dimension(662, 507));

        lbJumlah.setText(" Jumlah                  :");

        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });

        lbCatatan.setText("Catatan                  :");

        lbJenis.setText("Jenis                       :");

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDAPATAN", "PENGELUARAN" }));

        btnUbah.setBackground(new java.awt.Color(255, 165, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-edit-20.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 128, 0));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-add-20.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tbKas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKas);

        btnReset.setBackground(new java.awt.Color(0, 51, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-reset-20 (1).png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID :");

        txtID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-delete-20.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Pendapatan");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPendapatan.setForeground(new java.awt.Color(51, 204, 0));
        txtPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPendapatan.setText("0");
        txtPendapatan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSaldo.setText("0");
        txtSaldo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total Pengeluaran");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Saldo");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPengeluaran.setForeground(new java.awt.Color(255, 0, 0));
        txtPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPengeluaran.setText("0");
        txtPengeluaran.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnKasLayout = new javax.swing.GroupLayout(pnKas);
        pnKas.setLayout(pnKasLayout);
        pnKasLayout.setHorizontalGroup(
            pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(pnKasLayout.createSequentialGroup()
                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKasLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbJenis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCatatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbJumlah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnKasLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUbah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnHapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnReset))
                                .addComponent(tfCatatan)
                                .addComponent(cbJenis, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnKasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnKasLayout.createSequentialGroup()
                                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnKasLayout.setVerticalGroup(
            pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJumlah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCatatan)
                    .addComponent(tfCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnUbah)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, 0)
                .addGroup(pnKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPendapatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnKas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnKas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String jumlah = tfJumlah.getText();
        String catatan = tfCatatan.getText();
        String jenis = cbJenis.getSelectedItem().toString();
        String id = txtID.getText();
        String format = "yyyy-MM-dd HH:mm:ss";
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        String currentDateTime = sdf.format(new Date());  // Mendapatkan tanggal dan jam saat ini

        // Query SQL untuk memasukkan data ke tabel pembelian
        String sql = "UPDATE kas SET jumlah=?, catatan=?, jenis=?, waktu=? WHERE id_kas=?";

        try {
            Connection conn = Koneksi.konek();
            PreparedStatement ps = conn.prepareStatement(sql);

            // Set parameter untuk query SQL
            ps.setString(1, jumlah);
            ps.setString(2, catatan);
            ps.setString(3, jenis);
            ps.setString(4, currentDateTime);  // tanggal saat ini
            ps.setString(5, id);

            // Eksekusi query
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal di ubah: " + e.getMessage());
        }

        tampilTabel();
        reset();
        tampilRingkasan();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String jumlah = tfJumlah.getText();
        String catatan = tfCatatan.getText();
        String jenis = cbJenis.getSelectedItem().toString();
        String format = "yyyy-MM-dd HH:mm:ss";
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        String currentDateTime = sdf.format(new Date());  // Mendapatkan tanggal dan jam saat ini

        // Query SQL untuk memasukkan data ke tabel pembelian
        String sql = "INSERT INTO kas (jumlah, catatan, jenis, waktu) "
                + "VALUES (?, ?, ?, ?)";

        try {
            Connection conn = Koneksi.konek();
            PreparedStatement ps = conn.prepareStatement(sql);

            // Set parameter untuk query SQL
            ps.setString(1, jumlah);
            ps.setString(2, catatan);
            ps.setString(3, jenis);
            ps.setString(4, currentDateTime);  // tanggal saat ini

            // Eksekusi query
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
        }

        // Setelah data berhasil disimpan, tampilkan data di tabel atau reset form
        tampilTabel();
        reset();
        tampilRingkasan();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tbKasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKasMouseClicked
        int barisClick = tbKas.rowAtPoint(evt.getPoint());
        String id = tbKas.getValueAt(barisClick, 0).toString();
        String jumlah = tbKas.getValueAt(barisClick, 1).toString();
        String catatan = tbKas.getValueAt(barisClick, 2).toString();
        String jenis = tbKas.getValueAt(barisClick, 3).toString();
        txtID.setText(id);
        tfJumlah.setText(jumlah);
        tfCatatan.setText(catatan);
        cbJenis.setSelectedItem(jenis);
    }//GEN-LAST:event_tbKasMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String id = txtID.getText();
        String sql = "DELETE FROM kas WHERE id_kas=?";
        try {
            Connection conn = Koneksi.konek();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, id);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
        tampilTabel();
        reset();
        tampilRingkasan();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCatatan;
    private javax.swing.JLabel lbJenis;
    private javax.swing.JLabel lbJumlah;
    private javax.swing.JPanel pnKas;
    private javax.swing.JTable tbKas;
    private javax.swing.JTextField tfCatatan;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtPendapatan;
    private javax.swing.JLabel txtPengeluaran;
    private javax.swing.JLabel txtSaldo;
    // End of variables declaration//GEN-END:variables
}
