/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fuelin;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class MenuPetugas extends javax.swing.JFrame {

    int xx, xy;

    public MenuPetugas() {
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
        PanelGradient panel = new PanelGradient();
        panel.setBounds(0, 0, 400, 300);
        add(panel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new fuelin.PanelGradient();
        panelGradient2 = new fuelin.PanelGradient();
        panelGradient3 = new fuelin.PanelGradient();
        panelGradient4 = new fuelin.PanelGradient();
        pnKiri = new javax.swing.JPanel();
        lbFotoLogo = new javax.swing.JLabel();
        lbFuelin = new javax.swing.JLabel();
        pnDashboard = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JLabel();
        lgoDashboard = new javax.swing.JLabel();
        pnTransaksi = new javax.swing.JPanel();
        btnTransaksi = new javax.swing.JLabel();
        lgoTransaksi = new javax.swing.JLabel();
        pnStok = new javax.swing.JPanel();
        btnStok = new javax.swing.JLabel();
        lgoStok = new javax.swing.JLabel();
        pnLaporan = new javax.swing.JPanel();
        btnLaporan = new javax.swing.JLabel();
        lgoLaporan = new javax.swing.JLabel();
        pnAbout = new javax.swing.JPanel();
        btnAbout = new javax.swing.JLabel();
        lgoAbout = new javax.swing.JLabel();
        pnLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        lgoLogout = new javax.swing.JLabel();
        pnBarAtas = new javax.swing.JPanel();
        pnClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        pnMinimize = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JLabel();
        pnKanan = new javax.swing.JPanel();
        panelGradient5 = new fuelin.PanelGradient();
        pnDasar = new javax.swing.JPanel();
        pnUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnKiri.setBackground(new java.awt.Color(255, 255, 255));

        lbFotoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LogoMainMenu.png"))); // NOI18N
        lbFotoLogo.setText("jLabel1");

        lbFuelin.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lbFuelin.setForeground(new java.awt.Color(51, 51, 51));
        lbFuelin.setText("Fuelin");

        pnDashboard.setBackground(new java.awt.Color(255, 255, 255));

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(51, 51, 51));
        btnDashboard.setText("Dashboard");
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });

        lgoDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoDashboard.setForeground(new java.awt.Color(51, 51, 51));
        lgoDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-dashboard-25.png"))); // NOI18N

        javax.swing.GroupLayout pnDashboardLayout = new javax.swing.GroupLayout(pnDashboard);
        pnDashboard.setLayout(pnDashboardLayout);
        pnDashboardLayout.setHorizontalGroup(
            pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDashboardLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lgoDashboard)
                .addGap(10, 10, 10)
                .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDashboardLayout.setVerticalGroup(
            pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnTransaksi.setBackground(new java.awt.Color(255, 255, 255));

        btnTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        btnTransaksi.setText("Transaksi");
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        lgoTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        lgoTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-transaction-25.png"))); // NOI18N

        javax.swing.GroupLayout pnTransaksiLayout = new javax.swing.GroupLayout(pnTransaksi);
        pnTransaksi.setLayout(pnTransaksiLayout);
        pnTransaksiLayout.setHorizontalGroup(
            pnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransaksiLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lgoTransaksi)
                .addGap(10, 10, 10)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTransaksiLayout.setVerticalGroup(
            pnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnStok.setBackground(new java.awt.Color(255, 255, 255));

        btnStok.setBackground(new java.awt.Color(255, 255, 255));
        btnStok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStok.setForeground(new java.awt.Color(51, 51, 51));
        btnStok.setText("Kelola Stok");
        btnStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStokMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStokMouseExited(evt);
            }
        });

        lgoStok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoStok.setForeground(new java.awt.Color(51, 51, 51));
        lgoStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-stock-25.png"))); // NOI18N

        javax.swing.GroupLayout pnStokLayout = new javax.swing.GroupLayout(pnStok);
        pnStok.setLayout(pnStokLayout);
        pnStokLayout.setHorizontalGroup(
            pnStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStokLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lgoStok)
                .addGap(10, 10, 10)
                .addComponent(btnStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnStokLayout.setVerticalGroup(
            pnStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoStok, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnLaporan.setBackground(new java.awt.Color(255, 255, 255));

        btnLaporan.setBackground(new java.awt.Color(255, 255, 255));
        btnLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(51, 51, 51));
        btnLaporan.setText("Laporan");
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });

        lgoLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoLaporan.setForeground(new java.awt.Color(51, 51, 51));
        lgoLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-report-25.png"))); // NOI18N

        javax.swing.GroupLayout pnLaporanLayout = new javax.swing.GroupLayout(pnLaporan);
        pnLaporan.setLayout(pnLaporanLayout);
        pnLaporanLayout.setHorizontalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLaporanLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lgoLaporan)
                .addGap(10, 10, 10)
                .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnLaporanLayout.setVerticalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnAbout.setBackground(new java.awt.Color(255, 255, 255));

        btnAbout.setBackground(new java.awt.Color(255, 255, 255));
        btnAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(51, 51, 51));
        btnAbout.setText("About");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });

        lgoAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoAbout.setForeground(new java.awt.Color(51, 51, 51));
        lgoAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-about-25.png"))); // NOI18N

        pnLogout.setBackground(new java.awt.Color(255, 255, 255));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(51, 51, 51));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        lgoLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoLogout.setForeground(new java.awt.Color(51, 51, 51));
        lgoLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-logout-25.png"))); // NOI18N

        javax.swing.GroupLayout pnLogoutLayout = new javax.swing.GroupLayout(pnLogout);
        pnLogout.setLayout(pnLogoutLayout);
        pnLogoutLayout.setHorizontalGroup(
            pnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogoutLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lgoLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnLogoutLayout.setVerticalGroup(
            pnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnAboutLayout = new javax.swing.GroupLayout(pnAbout);
        pnAbout.setLayout(pnAboutLayout);
        pnAboutLayout.setHorizontalGroup(
            pnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAboutLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lgoAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(pnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnAboutLayout.setVerticalGroup(
            pnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAboutLayout.createSequentialGroup()
                .addGroup(pnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lgoAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(pnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnKiriLayout = new javax.swing.GroupLayout(pnKiri);
        pnKiri.setLayout(pnKiriLayout);
        pnKiriLayout.setHorizontalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbFotoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFuelin)
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(pnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnKiriLayout.setVerticalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbFotoLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFuelin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(pnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        getContentPane().add(pnKiri, java.awt.BorderLayout.LINE_START);

        pnBarAtas.setPreferredSize(new java.awt.Dimension(865, 25));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-close-20.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnCloseLayout = new javax.swing.GroupLayout(pnClose);
        pnClose.setLayout(pnCloseLayout);
        pnCloseLayout.setHorizontalGroup(
            pnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCloseLayout.setVerticalGroup(
            pnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-minimize-20.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnMinimizeLayout = new javax.swing.GroupLayout(pnMinimize);
        pnMinimize.setLayout(pnMinimizeLayout);
        pnMinimizeLayout.setHorizontalGroup(
            pnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMinimizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnMinimizeLayout.setVerticalGroup(
            pnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBarAtasLayout = new javax.swing.GroupLayout(pnBarAtas);
        pnBarAtas.setLayout(pnBarAtasLayout);
        pnBarAtasLayout.setHorizontalGroup(
            pnBarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBarAtasLayout.createSequentialGroup()
                .addContainerGap(815, Short.MAX_VALUE)
                .addComponent(pnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnBarAtasLayout.setVerticalGroup(
            pnBarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBarAtasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnBarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        getContentPane().add(pnBarAtas, java.awt.BorderLayout.PAGE_START);

        pnKanan.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelGradient5Layout = new javax.swing.GroupLayout(panelGradient5);
        panelGradient5.setLayout(panelGradient5Layout);
        panelGradient5Layout.setHorizontalGroup(
            panelGradient5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        panelGradient5Layout.setVerticalGroup(
            panelGradient5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pnKanan.add(panelGradient5, java.awt.BorderLayout.PAGE_START);

        pnUtama.setBackground(new java.awt.Color(255, 255, 255));
        pnUtama.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pnKanan.add(pnDasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnKanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        pnClose.setBackground(new Color(255, 0, 0));
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        pnClose.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        pnClose.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnCloseMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        pnMinimize.setBackground(new Color(204, 204, 204));
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        pnMinimize.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        pnMinimize.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        pnDashboard.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        pnDashboard.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        pnDashboard.setBackground(new Color(204, 204, 204));
        pnUtama.removeAll();
        pnUtama.add(new Dashboard());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        pnTransaksi.setBackground(new Color(204, 204, 204));
        pnUtama.removeAll();
        pnUtama.add(new Transaksi());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        pnTransaksi.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        pnTransaksi.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStokMouseClicked
        pnStok.setBackground(new Color(204, 204, 204));
        pnUtama.removeAll();
        pnUtama.add(new Stok());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnStokMouseClicked

    private void btnStokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStokMouseEntered
        pnStok.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnStokMouseEntered

    private void btnStokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStokMouseExited
        pnStok.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnStokMouseExited

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        pnLaporan.setBackground(new Color(204, 204, 204));
        pnUtama.removeAll();
        pnUtama.add(new Laporan());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
        pnLaporan.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited
        pnLaporan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnLaporanMouseExited

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        pnAbout.setBackground(new Color(204, 204, 204));
        String aboutFuelin = """
    ==============================
               About Fuelin
    ==============================
Nama Aplikasi  : Fuelin
Versi                    : 1.0.0
Dibuat oleh        : TIM 1 SI 2024 INSTITUT TEKNOLOGI MOJOSARI
Tanggal Rilis     : 19 Juli 2025

Deskripsi:
Fuelin adalah aplikasi manajemen SPBU Mini (Pom Mini)
yang membantu mencatat transaksi penjualan BBM,
mengelola stok bahan bakar, mencetak struk otomatis,
dan menghasilkan laporan penjualan harian, mingguan, bulanan,
serta rekap data secara akurat dan efisien.

Aplikasi ini dirancang ringan, mudah digunakan,
dan cocok untuk kebutuhan UMKM Pom Mini.

Kontak Bantuan :
Email : miftakhurozaq123@gmail.com
WhatsApp : 085655873785

Terima kasih telah menggunakan Fuelin!
    """;

        JOptionPane.showMessageDialog(null, aboutFuelin, "Tentang Aplikasi Fuelin", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        pnAbout.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        pnAbout.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?",
                "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            // Jika Yes, kembali ke login
            new FormLogin().setVisible(true);
            dispose(); // Menutup jendela saat ini
        } else if (response == JOptionPane.NO_OPTION) {
            // Jika No, kembali ke menu terakhir yang dibuka 
            // Misalnya, membuka kembali JFrame menu terakhir
            this.setVisible(true); // Menampilkan kembali menu yang sedang aktif
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        pnLogout.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        pnLogout.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnLaporan;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnStok;
    private javax.swing.JLabel btnTransaksi;
    private javax.swing.JLabel lbFotoLogo;
    private javax.swing.JLabel lbFuelin;
    private javax.swing.JLabel lgoAbout;
    private javax.swing.JLabel lgoDashboard;
    private javax.swing.JLabel lgoLaporan;
    private javax.swing.JLabel lgoLogout;
    private javax.swing.JLabel lgoStok;
    private javax.swing.JLabel lgoTransaksi;
    private fuelin.PanelGradient panelGradient1;
    private fuelin.PanelGradient panelGradient2;
    private fuelin.PanelGradient panelGradient3;
    private fuelin.PanelGradient panelGradient4;
    private fuelin.PanelGradient panelGradient5;
    private javax.swing.JPanel pnAbout;
    private javax.swing.JPanel pnBarAtas;
    private javax.swing.JPanel pnClose;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JPanel pnDashboard;
    private javax.swing.JPanel pnKanan;
    private javax.swing.JPanel pnKiri;
    private javax.swing.JPanel pnLaporan;
    private javax.swing.JPanel pnLogout;
    private javax.swing.JPanel pnMinimize;
    private javax.swing.JPanel pnStok;
    private javax.swing.JPanel pnTransaksi;
    private javax.swing.JPanel pnUtama;
    // End of variables declaration//GEN-END:variables
}
